# Generated by Django 4.0.4 on 2022-04-19 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_message_liked_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='liked',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
